# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '日历显示时间.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 536)
        self.label_1_time = QtWidgets.QLabel(Form)
        self.label_1_time.setGeometry(QtCore.QRect(90, 140, 54, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_1_time.setFont(font)
        self.label_1_time.setObjectName("label_1_time")
        self.label_2_date = QtWidgets.QLabel(Form)
        self.label_2_date.setGeometry(QtCore.QRect(90, 200, 54, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2_date.setFont(font)
        self.label_2_date.setObjectName("label_2_date")
        self.label_3_date_time = QtWidgets.QLabel(Form)
        self.label_3_date_time.setGeometry(QtCore.QRect(70, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3_date_time.setFont(font)
        self.label_3_date_time.setObjectName("label_3_date_time")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(160, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(160, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(160, 260, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.calendar = QtWidgets.QCalendarWidget(Form)
        self.calendar.setGeometry(QtCore.QRect(400, 30, 371, 251))
        self.calendar.setObjectName("calendar")
        self.btnReadNow = QtWidgets.QPushButton(Form)
        self.btnReadNow.setGeometry(QtCore.QRect(80, 30, 261, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnReadNow.setFont(font)
        self.btnReadNow.setObjectName("btnReadNow")
        self.label_4_calender = QtWidgets.QLabel(Form)
        self.label_4_calender.setGeometry(QtCore.QRect(400, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4_calender.setFont(font)
        self.label_4_calender.setObjectName("label_4_calender")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(540, 360, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1_time.setText(_translate("Form", "时间："))
        self.label_2_date.setText(_translate("Form", "日期："))
        self.label_3_date_time.setText(_translate("Form", "日期时间："))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy年M月d日"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "yyyy年M月d日 H:mm"))
        self.btnReadNow.setText(_translate("Form", "获取当前日期时间"))
        self.label_4_calender.setText(_translate("Form", "日历显示时间"))
